// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using The_Food_Works_WebAPI.Models;

#nullable disable

namespace The_Food_Works_WebAPI.Models
{
    public partial class BatchLine
    {
        public int ProductId { get; set; }
        public int BatchId { get; set; }
        public int Quantity { get; set; }

        public virtual Batch Batch { get; set; }
        public virtual Product Product { get; set; }
    }
}