// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace The_Food_Works_WebAPI.Models
{
    public partial class Branch
    {
        public Branch()
        {
            BranchAddress = new HashSet<BranchAddress>();
            BranchProduct = new HashSet<BranchProduct>();
            BranchRequest = new HashSet<BranchRequest>();
            BranchRequestLine = new HashSet<BranchRequestLine>();
            Employee = new HashSet<Employee>();
            Sale = new HashSet<Sale>();
            WriteOffProduct = new HashSet<WriteOffProduct>();
        }

        public int BranchId { get; set; }
        public string BranchName { get; set; }
        public string BranchContactNumber { get; set; }
        public string BranchEmailAddress { get; set; }
        public string BranchImage { get; set; }
        public bool BranchStatus { get; set; }

        public virtual ICollection<BranchAddress> BranchAddress { get; set; }
        public virtual ICollection<BranchProduct> BranchProduct { get; set; }
        public virtual ICollection<BranchRequest> BranchRequest { get; set; }
        public virtual ICollection<BranchRequestLine> BranchRequestLine { get; set; }
        public virtual ICollection<Employee> Employee { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual ICollection<WriteOffProduct> WriteOffProduct { get; set; }
    }
}