// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace The_Food_Works_WebAPI.Models
{
    public partial class Customer
    {
        public Customer()
        {
            Cart = new HashSet<Cart>();
            CustomerAddress = new HashSet<CustomerAddress>();
            LoyaltyDate = new HashSet<LoyaltyDate>();
            ProductReview = new HashSet<ProductReview>();
            Sale = new HashSet<Sale>();
            User = new HashSet<User>();
            Voucher = new HashSet<Voucher>();
        }

        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerSurname { get; set; }
        public DateTime? CustomerDob { get; set; }
        public string CustomerTelephone { get; set; }
        public string CustomerEmail { get; set; }
        public bool IsLoyaltyProgram { get; set; }

        public virtual ICollection<Cart> Cart { get; set; }
        public virtual ICollection<CustomerAddress> CustomerAddress { get; set; }
        public virtual ICollection<LoyaltyDate> LoyaltyDate { get; set; }
        public virtual ICollection<ProductReview> ProductReview { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}