// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace The_Food_Works_WebAPI.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Batch = new HashSet<Batch>();
            Delivery = new HashSet<Delivery>();
            EmployeeTrainingModule = new HashSet<EmployeeTrainingModule>();
            Sale = new HashSet<Sale>();
            User = new HashSet<User>();
        }

        public int EmployeeId { get; set; }
        public string EmployeeName { get; set; }
        public string EmployeeSurname { get; set; }
        public string EmployeeIdNumber { get; set; }
        public string EmployeeTelephone { get; set; }
        public string EmployeeEmail { get; set; }
        public int BranchId { get; set; }

        public virtual Branch Branch { get; set; }
        public virtual ICollection<Batch> Batch { get; set; }
        public virtual ICollection<Delivery> Delivery { get; set; }
        public virtual ICollection<EmployeeTrainingModule> EmployeeTrainingModule { get; set; }
        public virtual ICollection<Sale> Sale { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}