// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace The_Food_Works_WebAPI.Models
{
    public partial class TrainingModuleType
    {
        public TrainingModuleType()
        {
            TrainingModules = new HashSet<TrainingModule>();
        }

        public int TrainingModuleTypeId { get; set; }
        public string TrainingModuleTypeDescription { get; set; }

        public virtual ICollection<TrainingModule> TrainingModules { get; set; }
    }
}