// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace The_Food_Works_WebAPI.Models
{

    public partial class UserRole
    {
        public UserRole()
        {
            User = new HashSet<User>();
        }

        public int UserRoleId { get; set; }
        public string UserRoleName { get; set; }
        public string UserRoleDescription { get; set; }

        public virtual ICollection<User> User { get; set; }
    }
}